{% set name = "synthsr" %}
{% set version = "2.0" %}
{% set ref = "5d415986d849e98c029b4105f531221a2aa46968" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dhananjhay/SynthSR/archive/{{ ref }}.tar.gz
  sha256: e6e1b5e71a3f3fedfd652f288db9cd520c8bbab95a0d8fe5ce7d4700d2ce558a

build:
  noarch: python
  number: 0
  skip: true  # [win]

requirements:
  host:
    - python
  run:
    - python >=3.8,<3.9
    - tensorflow-gpu==2.2.0 
    - keras==2.3.1 
    - protobuf==3.20.3 
    - numpy==1.19.5 
    - nibabel==5.0.1 
    - matplotlib==3.6.2

test:
  commands:
    - ls ${SRC_DIR}
    - python ${SRC_DIR}/work_moved_synthsr-2.0-py_0_noarch/scripts/predict_command_line.py --help


about:
  home: https://github.com/BBillot/SynthSR
  summary: |
    A convolutional neural network that turns a clinical MRI scan 
    (or even CT scan!) of any orientation, resolution and contrast 
    into 1 mm isotropic MP-RAGE, while inpainting lesions (which 
    enables easier segmentation, registration, etc).
  description: |
    Domain Randomisation for Segmentation of Brain MRI Scans of any 
    Contrast and Resolution. 
  license: Apache-2.0
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - Dhananjhay