{% set name = "synthsr" %}
{% set version = "2.0" %}
{% set ref = "2662de27e370e91ab8df8d5fba299e5f5a5234be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dhananjhay/SynthSR/archive/{{ ref }}.tar.gz
  sha256: 0a3c35131561375948ed6976ae26e7c33ea22bd4007ae71ebb2584c1c75355b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python =3.6
    - pip
    - setuptools
  run:
    - python =3.8
    - tensorflow-gpu==2.2.0 
    - keras==2.3.1 
    - numpy<1.20
    - nibabel
    - matplotlib
    - scipy >=1.9.0

test:
  commands:
    - python -m SynthSR.scripts.predict_command_line --help

about:
  home: https://github.com/BBillot/SynthSR
  summary: |
    A convolutional neural network that turns a clinical MRI scan 
    (or even CT scan!) of any orientation, resolution and contrast 
    into 1 mm isotropic MP-RAGE, while inpainting lesions (which 
    enables easier segmentation, registration, etc).
  description: |
    Domain Randomisation for Segmentation of Brain MRI Scans of any 
    Contrast and Resolution. 
  license: Apache-2.0
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - Dhananjhay