{% set name = "nighres" %}
{% set version = "1.5.1" %}
{% set ref = "ea6dd98235e2a62b30768a3107b4365875536f13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nighres/nighres/archive/{{ ref }}.tar.gz
  sha256: c9f66feb90810b140fe5cd83cee5971104816aa3f9b506e1284e48d1b6035812

build:
  skip: true  # [py<38]
  skip: true  # [win]
  number: 0

requirements:
  build:
    - patchelf
    - {{ compiler('cxx') }}
    - wget
    - tar
    - wheel
    - jcc
    - openjdk
  host:
    - python
    - pip
    - jcc
    - openjdk
  run:
    - python
    - numpy >=1.22.3
    - nibabel >=3.2.2
    - psutil >=5.9.0
    - antspyx >=0.3.2
    - dipy >=1.5.0
    - jcc
    - openjdk

test:
  imports:
    - nighres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://nighres.readthedocs.io/
  summary: Nighres is a Python package for processing of high-resolution neuroimaging data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dhananjhay
