{% set name = "hippunfold" %}
{% set version = "2.0.0" %}
{% set ref = "c09494af2a76e794f3443f508d25c515a5d1dfd2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/khanlab/hippunfold/archive/{{ ref }}.tar.gz
  sha256: b2f9d105b7d68c33d4e29c87f425f134ea98a2f8ffe01dbe0edd9ae3a55d6a60

build:
  entry_points: 
    - hippunfold = hippunfold.run:app.run
    - hippunfold-quick = hippunfold.run_quick:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage("hippunfold", max_pin="x") }} 

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python >=3.11,<4.0
    - snakebids >=0.14.0
    - appdirs >=1.4.4,<2.0.0
    - pyvista >=0.44.2,<0.45.0


test:
  imports:
    - hippunfold
  commands:
    - hippunfold --help
    - hippunfold-quick --help


about:
  home: https://github.com/khanlab/hippunfold
  summary: |
    This tool aims to automatically model the topological folding 
    structure of the human hippocampus, and computationally unfold it. 
  description: |
    This tool aims to automatically model the topological folding structure 
    of the human hippocampus, and computationally unfold it. 
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - Dhananjhay